/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "editor",
  "reporter",
]);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "draft",
  "published",
]);
export const enum_epapers_status = pgEnum("enum_epapers_status", [
  "draft",
  "published",
]);
export const enum_breaking_news_items_duration_minutes = pgEnum(
  "enum_breaking_news_items_duration_minutes",
  ["30", "60", "90", "120", "180", "360"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    role: enum_users_role("role").notNull().default("reporter"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    bio: varchar("bio"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_avatar_idx").on(columns.avatar),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_medium_url: varchar("sizes_medium_url"),
    sizes_medium_width: numeric("sizes_medium_width", { mode: "number" }),
    sizes_medium_height: numeric("sizes_medium_height", { mode: "number" }),
    sizes_medium_mimeType: varchar("sizes_medium_mime_type"),
    sizes_medium_filesize: numeric("sizes_medium_filesize", { mode: "number" }),
    sizes_medium_filename: varchar("sizes_medium_filename"),
    sizes_large_url: varchar("sizes_large_url"),
    sizes_large_width: numeric("sizes_large_width", { mode: "number" }),
    sizes_large_height: numeric("sizes_large_height", { mode: "number" }),
    sizes_large_mimeType: varchar("sizes_large_mime_type"),
    sizes_large_filesize: numeric("sizes_large_filesize", { mode: "number" }),
    sizes_large_filename: varchar("sizes_large_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_medium_sizes_medium_filename_idx").on(
      columns.sizes_medium_filename,
    ),
    index("media_sizes_large_sizes_large_filename_idx").on(
      columns.sizes_large_filename,
    ),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    color: varchar("color").default("#01284E"),
    displayOrder: numeric("display_order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const articles_tags = pgTable(
  "articles_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    tag: varchar("tag"),
  },
  (columns) => [
    index("articles_tags_order_idx").on(columns._order),
    index("articles_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [articles.id],
      name: "articles_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    excerpt: varchar("excerpt"),
    content: jsonb("content").notNull(),
    featuredImage: integer("featured_image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    category: integer("category_id")
      .notNull()
      .references(() => categories.id, {
        onDelete: "set null",
      }),
    reporter: integer("reporter_id").references(() => users.id, {
      onDelete: "set null",
    }),
    publishDate: timestamp("publish_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    status: enum_articles_status("status").notNull().default("draft"),
    isFeatured: boolean("is_featured").default(false),
    isBreaking: boolean("is_breaking").default(false),
    viewCount: numeric("view_count", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_featured_image_idx").on(columns.featuredImage),
    index("articles_category_idx").on(columns.category),
    index("articles_reporter_idx").on(columns.reporter),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
  ],
);

export const epapers_pages_article_clips_clip_images = pgTable(
  "epapers_pages_article_clips_clip_images",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    caption: varchar("caption"),
  },
  (columns) => [
    index("epapers_pages_article_clips_clip_images_order_idx").on(
      columns._order,
    ),
    index("epapers_pages_article_clips_clip_images_parent_id_idx").on(
      columns._parentID,
    ),
    index("epapers_pages_article_clips_clip_images_image_idx").on(
      columns.image,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [epapers_pages_article_clips.id],
      name: "epapers_pages_article_clips_clip_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const epapers_pages_article_clips = pgTable(
  "epapers_pages_article_clips",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    title: varchar("title").notNull(),
    zoneX: numeric("zone_x", { mode: "number" }),
    zoneY: numeric("zone_y", { mode: "number" }),
    zoneW: numeric("zone_w", { mode: "number" }),
    zoneH: numeric("zone_h", { mode: "number" }),
    continuedFrom: varchar("continued_from"),
    linkedArticleSlug: varchar("linked_article_slug"),
  },
  (columns) => [
    index("epapers_pages_article_clips_order_idx").on(columns._order),
    index("epapers_pages_article_clips_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [epapers_pages.id],
      name: "epapers_pages_article_clips_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const epapers_pages = pgTable(
  "epapers_pages",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    pageImage: integer("page_image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    pageNumber: numeric("page_number", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("epapers_pages_order_idx").on(columns._order),
    index("epapers_pages_parent_id_idx").on(columns._parentID),
    index("epapers_pages_page_image_idx").on(columns.pageImage),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [epapers.id],
      name: "epapers_pages_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const epapers = pgTable(
  "epapers",
  {
    id: serial("id").primaryKey(),
    issueDate: timestamp("issue_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    headerZonePageNumber: numeric("header_zone_page_number", {
      mode: "number",
    }),
    headerZoneX: numeric("header_zone_x", { mode: "number" }),
    headerZoneY: numeric("header_zone_y", { mode: "number" }),
    headerZoneW: numeric("header_zone_w", { mode: "number" }),
    headerZoneH: numeric("header_zone_h", { mode: "number" }),
    footerZonePageNumber: numeric("footer_zone_page_number", {
      mode: "number",
    }),
    footerZoneX: numeric("footer_zone_x", { mode: "number" }),
    footerZoneY: numeric("footer_zone_y", { mode: "number" }),
    footerZoneW: numeric("footer_zone_w", { mode: "number" }),
    footerZoneH: numeric("footer_zone_h", { mode: "number" }),
    pageCount: numeric("page_count", { mode: "number" }),
    status: enum_epapers_status("status").notNull().default("draft"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("epapers_issue_date_idx").on(columns.issueDate),
    index("epapers_updated_at_idx").on(columns.updatedAt),
    index("epapers_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    categoriesID: integer("categories_id"),
    articlesID: integer("articles_id"),
    epapersID: integer("epapers_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    index("payload_locked_documents_rels_epapers_id_idx").on(columns.epapersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["epapersID"]],
      foreignColumns: [epapers.id],
      name: "payload_locked_documents_rels_epapers_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: serial("id").primaryKey(),
    siteName: varchar("site_name").notNull().default("নিউ টাইমস"),
    tagline: varchar("tagline").default("সত্য ও নিরপেক্ষ সংবাদের প্রতিশ্রুতি"),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    socialLinks_facebook: varchar("social_links_facebook"),
    socialLinks_youtube: varchar("social_links_youtube"),
    socialLinks_twitter: varchar("social_links_twitter"),
    socialLinks_instagram: varchar("social_links_instagram"),
    socialLinks_linkedin: varchar("social_links_linkedin"),
    contactInfo_phone: varchar("contact_info_phone"),
    contactInfo_email: varchar("contact_info_email"),
    contactInfo_address: varchar("contact_info_address"),
    editorInfo_chiefEditor: varchar("editor_info_chief_editor"),
    editorInfo_editor: varchar("editor_info_editor"),
    editorInfo_publisherInfo: varchar("editor_info_publisher_info"),
    footerText: varchar("footer_text").default(
      "স্বত্ব © ২০২৬ দৈনিক নিউ টাইমস কর্তৃক সর্বসত্ব স্বত্বাধিকার সংরক্ষিত।",
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("site_settings_logo_idx").on(columns.logo)],
);

export const headlines_items = pgTable(
  "headlines_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text").notNull(),
    link: varchar("link"),
    isActive: boolean("is_active").default(true),
  },
  (columns) => [
    index("headlines_items_order_idx").on(columns._order),
    index("headlines_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [headlines.id],
      name: "headlines_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const headlines = pgTable("headlines", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const breaking_news_items = pgTable(
  "breaking_news_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text").notNull(),
    link: varchar("link"),
    durationMinutes: enum_breaking_news_items_duration_minutes(
      "duration_minutes",
    )
      .notNull()
      .default("60"),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    isActive: boolean("is_active").default(true),
  },
  (columns) => [
    index("breaking_news_items_order_idx").on(columns._order),
    index("breaking_news_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [breaking_news.id],
      name: "breaking_news_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const breaking_news = pgTable("breaking_news", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_categories = relations(categories, () => ({}));
export const relations_articles_tags = relations(articles_tags, ({ one }) => ({
  _parentID: one(articles, {
    fields: [articles_tags._parentID],
    references: [articles.id],
    relationName: "tags",
  }),
}));
export const relations_articles = relations(articles, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [articles.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  category: one(categories, {
    fields: [articles.category],
    references: [categories.id],
    relationName: "category",
  }),
  reporter: one(users, {
    fields: [articles.reporter],
    references: [users.id],
    relationName: "reporter",
  }),
  tags: many(articles_tags, {
    relationName: "tags",
  }),
}));
export const relations_epapers_pages_article_clips_clip_images = relations(
  epapers_pages_article_clips_clip_images,
  ({ one }) => ({
    _parentID: one(epapers_pages_article_clips, {
      fields: [epapers_pages_article_clips_clip_images._parentID],
      references: [epapers_pages_article_clips.id],
      relationName: "clipImages",
    }),
    image: one(media, {
      fields: [epapers_pages_article_clips_clip_images.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_epapers_pages_article_clips = relations(
  epapers_pages_article_clips,
  ({ one, many }) => ({
    _parentID: one(epapers_pages, {
      fields: [epapers_pages_article_clips._parentID],
      references: [epapers_pages.id],
      relationName: "articleClips",
    }),
    clipImages: many(epapers_pages_article_clips_clip_images, {
      relationName: "clipImages",
    }),
  }),
);
export const relations_epapers_pages = relations(
  epapers_pages,
  ({ one, many }) => ({
    _parentID: one(epapers, {
      fields: [epapers_pages._parentID],
      references: [epapers.id],
      relationName: "pages",
    }),
    pageImage: one(media, {
      fields: [epapers_pages.pageImage],
      references: [media.id],
      relationName: "pageImage",
    }),
    articleClips: many(epapers_pages_article_clips, {
      relationName: "articleClips",
    }),
  }),
);
export const relations_epapers = relations(epapers, ({ many }) => ({
  pages: many(epapers_pages, {
    relationName: "pages",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    epapersID: one(epapers, {
      fields: [payload_locked_documents_rels.epapersID],
      references: [epapers.id],
      relationName: "epapers",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings = relations(site_settings, ({ one }) => ({
  logo: one(media, {
    fields: [site_settings.logo],
    references: [media.id],
    relationName: "logo",
  }),
}));
export const relations_headlines_items = relations(
  headlines_items,
  ({ one }) => ({
    _parentID: one(headlines, {
      fields: [headlines_items._parentID],
      references: [headlines.id],
      relationName: "items",
    }),
  }),
);
export const relations_headlines = relations(headlines, ({ many }) => ({
  items: many(headlines_items, {
    relationName: "items",
  }),
}));
export const relations_breaking_news_items = relations(
  breaking_news_items,
  ({ one }) => ({
    _parentID: one(breaking_news, {
      fields: [breaking_news_items._parentID],
      references: [breaking_news.id],
      relationName: "items",
    }),
  }),
);
export const relations_breaking_news = relations(breaking_news, ({ many }) => ({
  items: many(breaking_news_items, {
    relationName: "items",
  }),
}));

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_articles_status: typeof enum_articles_status;
  enum_epapers_status: typeof enum_epapers_status;
  enum_breaking_news_items_duration_minutes: typeof enum_breaking_news_items_duration_minutes;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  categories: typeof categories;
  articles_tags: typeof articles_tags;
  articles: typeof articles;
  epapers_pages_article_clips_clip_images: typeof epapers_pages_article_clips_clip_images;
  epapers_pages_article_clips: typeof epapers_pages_article_clips;
  epapers_pages: typeof epapers_pages;
  epapers: typeof epapers;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings: typeof site_settings;
  headlines_items: typeof headlines_items;
  headlines: typeof headlines;
  breaking_news_items: typeof breaking_news_items;
  breaking_news: typeof breaking_news;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_categories: typeof relations_categories;
  relations_articles_tags: typeof relations_articles_tags;
  relations_articles: typeof relations_articles;
  relations_epapers_pages_article_clips_clip_images: typeof relations_epapers_pages_article_clips_clip_images;
  relations_epapers_pages_article_clips: typeof relations_epapers_pages_article_clips;
  relations_epapers_pages: typeof relations_epapers_pages;
  relations_epapers: typeof relations_epapers;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings: typeof relations_site_settings;
  relations_headlines_items: typeof relations_headlines_items;
  relations_headlines: typeof relations_headlines;
  relations_breaking_news_items: typeof relations_breaking_news_items;
  relations_breaking_news: typeof relations_breaking_news;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
